### ISSUE TITLE
Invalid value in Retry annotation may lead to ClassCastException

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/lsp4mp#235]
This code is making the assumption that user entered an integer value but if he entered something else that would lead to ClassCastException

https://github.com/eclipse/lsp4mp/blob/f54b7355be2797ec8843e7d106cb4af0296a2ba6/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/faulttolerance/java/MicroProfileFaultToleranceASTValidator.java#L287

**Comment by rgrunber** [comment]
```
SEVERE: Error while visiting node with org.eclipse.lsp4mp.jdt.internal.faulttolerance.java.MicroProfileFaultToleranceASTValidator
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
	at org.eclipse.lsp4mp.jdt.internal.faulttolerance.java.MicroProfileFaultToleranceASTValidator.validateRetryAnnotation(MicroProfileFaultToleranceASTValidator.java:287)
	at org.eclipse.lsp4mp.jdt.internal.faulttolerance.java.MicroProfileFaultToleranceASTValidator.validateMethod(MicroProfileFaultToleranceASTValidator.java:186)
	at org.eclipse.lsp4mp.jdt.internal.faulttolerance.java.MicroProfileFaultToleranceASTValidator.visit(MicroProfileFaultToleranceASTValidator.java:122)
	at org.eclipse.lsp4mp.jdt.internal.core.java.validators.MultiASTVisitor.visit(MultiASTVisitor.java:118)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:653)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3251)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:499)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3251)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.lsp4mp.jdt.internal.core.java.validators.JavaASTDiagnosticsParticipant.collectDiagnosticsInFile(JavaASTDiagnosticsParticipant.java:58)
	at org.eclipse.lsp4mp.jdt.internal.core.java.validators.JavaASTDiagnosticsParticipant.collectDiagnostics(JavaASTDiagnosticsParticipant.java:45)
	at org.eclipse.lsp4mp.jdt.internal.core.java.diagnostics.JavaDiagnosticsDefinition.collectDiagnostics(JavaDiagnosticsDefinition.java:62)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManagerForJava.lambda$12(PropertiesManagerForJava.java:313)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManagerForJava.collectDiagnostics(PropertiesManagerForJava.java:312)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManagerForJava.diagnostics(PropertiesManagerForJava.java:286)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandlerForJava.getDiagnosticsForJava(MicroProfileDelegateCommandHandlerForJava.java:342)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandlerForJava.executeCommand(MicroProfileDelegateCommandHandlerForJava.java:86)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:525)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```
