### ISSUE TITLE
AnnotationAtttributeRule may fail on attribute values

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/lsp4mp#249]
https://github.com/eclipse/lsp4mp/blob/2d7c54fb9c04d640bc778d51bac0300be970fb33/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/core/java/validators/annotations/AnnotationAttributeRule.java#L87

This class is parsing the attribute value as a double. But the value maybe 123L or 2 * 3 or 1_000_000 which would cause an exception.

See https://github.com/redhat-developer/intellij-quarkus/issues/596

**Comment by angelozerr** [comment]
@JessicaJHee do you think you could take care of this issue?

**Comment by JessicaJHee** [comment]
Yes sounds good!

**Comment by rgrunber** [comment]
Ran into this exact error when checking the standard error logs.

```
Jun. 22, 2022 1:55:50 P.M. org.eclipse.lsp4mp.jdt.internal.core.java.validators.MultiASTVisitor visit
SEVERE: Error while visiting node with org.eclipse.lsp4mp.jdt.internal.core.java.validators.annotations.AnnotationRulesJavaASTValidator
java.lang.NumberFormatException: For input string: ""test""
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(Unknown Source)
	at java.base/java.lang.Double.parseDouble(Unknown Source)
	at org.eclipse.lsp4mp.jdt.internal.core.java.validators.annotations.AnnotationAttributeRule.validate(AnnotationAttributeRule.java:87)
	at org.eclipse.lsp4mp.jdt.internal.core.java.validators.annotations.AnnotationValidator.validate(AnnotationValidator.java:83)
	at org.eclipse.lsp4mp.jdt.internal.core.java.validators.JavaASTValidatorRegistry.validate(JavaASTValidatorRegistry.java:94)
	at org.eclipse.lsp4mp.jdt.internal.core.java.validators.annotations.AnnotationRulesJavaASTValidator.validateAnnotationAttributeValue(AnnotationRulesJavaASTValidator.java:106)
	at org.eclipse.lsp4mp.jdt.internal.core.java.validators.annotations.AnnotationRulesJavaASTValidator.validateAnnotation(AnnotationRulesJavaASTValidator.java:74)
	at org.eclipse.lsp4mp.jdt.internal.core.java.validators.annotations.AnnotationRulesJavaASTValidator.visit(AnnotationRulesJavaASTValidator.java:57)
	at org.eclipse.lsp4mp.jdt.internal.core.java.validators.MultiASTVisitor.visit(MultiASTVisitor.java:70)
	at org.eclipse.jdt.core.dom.NormalAnnotation.accept0(NormalAnnotation.java:149)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3251)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:660)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3251)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:499)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3251)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.lsp4mp.jdt.internal.core.java.validators.JavaASTDiagnosticsParticipant.collectDiagnosticsInFile(JavaASTDiagnosticsParticipant.java:58)
	at org.eclipse.lsp4mp.jdt.internal.core.java.validators.JavaASTDiagnosticsParticipant.collectDiagnostics(JavaASTDiagnosticsParticipant.java:45)
	at org.eclipse.lsp4mp.jdt.internal.core.java.diagnostics.JavaDiagnosticsDefinition.collectDiagnostics(JavaDiagnosticsDefinition.java:62)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManagerForJava.lambda$12(PropertiesManagerForJava.java:313)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManagerForJava.collectDiagnostics(PropertiesManagerForJava.java:312)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManagerForJava.diagnostics(PropertiesManagerForJava.java:286)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandlerForJava.getDiagnosticsForJava(MicroProfileDelegateCommandHandlerForJava.java:342)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandlerForJava.executeCommand(MicroProfileDelegateCommandHandlerForJava.java:86)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:527)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

The root cause of this is arguably not on the line mentioned above, but a few calls before that.
