### ISSUE TITLE
application.properties fails to load on start up

### ISSUE THREAD

**Issue by JessicaJHee** [eclipse/lsp4mp#266]
When opening a project (ex: config-quickstart), there is the following request failure after opening the application.properties file.

```
WARNING: Error while getting MicroProfileProjectInfo (classpath) for '.../application.properties'
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request microprofile/projectInfo failed with message: class java.lang.NoSuchMethodError cannot be cast to class java.lang.Exception (java.lang.NoSuchMethodError and java.lang.Exception are in module java.base of loader 'bootstrap')
```

**Comment by angelozerr** [comment]
@JessicaJHee is it a new bug?

**Comment by rgrunber** [comment]
I see it as well on latest versions of the language server :

```
[Trace - 12:32:21 p.m.] Sending response 'microprofile/projectInfo - (10)'. Processing request took 543ms
Jul. 04, 2022 12:32:21 P.M. org.eclipse.lsp4mp.ls.properties.MicroProfileProjectInfoCache lambda$getProjectInfo$0
WARNING: Error while getting MicroProfileProjectInfo (classpath) for 'file:///home/rgrunber/sample-projects/quarkus-quickstarts/config-quickstart/src/main/resources/application.properties'
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request microprofile/projectInfo failed with message: class java.lang.NoSuchMethodError cannot be cast to class java.lang.Exception (java.lang.NoSuchMethodError and java.lang.Exception are in module java.base of loader 'bootstrap')
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4mp.ls.commons.ParentProcessWatcher.lambda$apply$0(ParentProcessWatcher.java:148)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request microprofile/projectInfo failed with message: class java.lang.NoSuchMethodError cannot be cast to class java.lang.Exception (java.lang.NoSuchMethodError and java.lang.Exception are in module java.base of loader 'bootstrap')
	... 11 more
```

**Comment by rgrunber** [comment]
Ah, this is happening in JDT-LS :

```
!ENTRY org.eclipse.core.jobs 4 2 2022-07-04 12:32:21.409
!MESSAGE An internal error occurred during: "MicroProfile properties collector".
!STACK 0
java.lang.NoSuchMethodError: 'java.lang.String org.eclipse.m2e.core.embedder.ArtifactKey.getGroupId()'
	at org.eclipse.lsp4mp.jdt.internal.core.utils.DependencyUtil.getLocalArtifactFile(DependencyUtil.java:91)
	at org.eclipse.lsp4mp.jdt.internal.core.utils.DependencyUtil.getArtifact(DependencyUtil.java:63)
	at org.eclipse.lsp4mp.jdt.internal.core.MavenArtifactResolver.getArtifact(MavenArtifactResolver.java:44)
	at com.redhat.microprofile.jdt.internal.quarkus.core.properties.QuarkusConfigRootProvider.addArtifactInClasspath(QuarkusConfigRootProvider.java:178)
	at com.redhat.microprofile.jdt.internal.quarkus.core.properties.QuarkusConfigRootProvider.contributeToClasspath(QuarkusConfigRootProvider.java:160)
	at com.redhat.microprofile.jdt.internal.quarkus.core.properties.QuarkusConfigRootProvider.contributeToClasspath(QuarkusConfigRootProvider.java:102)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.contributeToClasspath(PropertiesManager.java:346)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getJavaProject(PropertiesManager.java:324)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.configureSearchClasspath(PropertiesManager.java:179)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:135)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:110)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:101)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.lambda$0(MicroProfileDelegateCommandHandler.java:105)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by rgrunber** [comment]
Please see the following change I had to make https://github.com/eclipse/eclipse.jdt.ls/commit/d2579803f384a0ea673a39dd2d0f224050e80db4 . The target platform for lsp4mp should also be updated so that this change is visible as a compilation error.

**Comment by rgrunber** [comment]
Should be resolved now. Need to JAVA_HOME is set to a JDK >= 17 or else it will still fail. Some inconsistent tests that may need to be fixed also.
