### ISSUE TITLE
Hovering over properties file fails with NullPointerException

### ISSUE THREAD

**Issue by jayadeepk** [eclipse/lsp4mp#341]
I installed Tools for MicroProfile (v0.6.0) and Quarkus (v1.12.0) extensions in VS Code. When I hover over quarkus application.properties, I get the following error:

```java
Jan 13, 2023 2:00:37 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "unresolvedValue" is null
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "unresolvedValue" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "unresolvedValue" is null
	at org.eclipse.lsp4mp.commons.utils.PropertyValueExpander$PropertyGraph.<init>(PropertyValueExpander.java:153)
	at org.eclipse.lsp4mp.commons.utils.PropertyValueExpander.<init>(PropertyValueExpander.java:56)
	at org.eclipse.lsp4mp.services.properties.PropertiesFileHover.getPropertyKeyHover(PropertiesFileHover.java:154)
	at org.eclipse.lsp4mp.services.properties.PropertiesFileHover.doHover(PropertiesFileHover.java:101)
	at org.eclipse.lsp4mp.services.properties.PropertiesFileLanguageService.doHover(PropertiesFileLanguageService.java:106)
	at org.eclipse.lsp4mp.ls.properties.PropertiesFileTextDocumentService.lambda$hover$3(PropertiesFileTextDocumentService.java:162)
	at org.eclipse.lsp4mp.ls.commons.ModelTextDocuments.lambda$computeModelAsync$0(ModelTextDocuments.java:121)
	... 7 more

[Error - 2:00:37 AM] Request textDocument/hover failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "unresolvedValue" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "unresolvedValue" is null
	at org.eclipse.lsp4mp.commons.utils.PropertyValueExpander$PropertyGraph.<init>(PropertyValueExpander.java:153)
	at org.eclipse.lsp4mp.commons.utils.PropertyValueExpander.<init>(PropertyValueExpander.java:56)
	at org.eclipse.lsp4mp.services.properties.PropertiesFileHover.getPropertyKeyHover(PropertiesFileHover.java:154)
	at org.eclipse.lsp4mp.services.properties.PropertiesFileHover.doHover(PropertiesFileHover.java:101)
	at org.eclipse.lsp4mp.services.properties.PropertiesFileLanguageService.doHover(PropertiesFileLanguageService.java:106)
	at org.eclipse.lsp4mp.ls.properties.PropertiesFileTextDocumentService.lambda$hover$3(PropertiesFileTextDocumentService.java:162)
	at org.eclipse.lsp4mp.ls.commons.ModelTextDocuments.lambda$computeModelAsync$0(ModelTextDocuments.java:121)
	... 7 more
```

**Comment by angelozerr** [comment]
Could you share your project and tell us which property you are hovering please.

**Comment by jayadeepk** [comment]
Hello @angelozerr ,
```
git clone https://github.com/quarkusio/quarkus-quickstarts.git
cd quarkus-quickstarts/security-openid-connect-web-authentication-quickstart
code .
```
After VS Code loads the Java project, open `src/main/resources/application.properties` and hover over any property.

<p><details><summary>My extensions list</summary>

```
eamodio.gitlens@13.2.0
ms-azuretools.vscode-docker@1.23.3
ms-iot.vscode-ros@0.8.4
ms-python.isort@2022.8.0
ms-python.python@2022.20.2
ms-python.vscode-pylance@2023.1.20
ms-toolsai.jupyter@2022.11.1003412109
ms-toolsai.jupyter-keymap@1.0.0
ms-toolsai.jupyter-renderers@1.0.12
ms-toolsai.vscode-jupyter-cell-tags@0.1.6
ms-toolsai.vscode-jupyter-slideshow@0.1.5
ms-vscode-remote.remote-containers@0.266.1
ms-vscode-remote.remote-ssh@0.94.0
ms-vscode-remote.remote-ssh-edit@0.84.0
ms-vscode-remote.remote-wsl@0.72.0
ms-vscode-remote.vscode-remote-extensionpack@0.23.0
ms-vscode.cpptools@1.13.9
ms-vscode.cpptools-extension-pack@1.3.0
ms-vscode.cpptools-themes@2.0.0
ms-vscode.remote-explorer@0.0.3
redhat.java@1.13.0
redhat.vscode-microprofile@0.6.0
redhat.vscode-quarkus@1.12.0
shardulm94.trailing-spaces@0.4.1
twxs.cmake@0.0.17
VisualStudioExptTeam.intellicode-api-usage-examples@0.2.6
VisualStudioExptTeam.vscodeintellicode@1.2.30
vscjava.vscode-java-debug@0.47.0
vscjava.vscode-java-dependency@0.21.1
vscjava.vscode-java-pack@0.25.7
vscjava.vscode-java-test@0.37.1
vscjava.vscode-maven@0.40.3
vscode-icons-team.vscode-icons@12.0.1
vscodevim.vim@1.24.3
yzhang.markdown-all-in-one@3.5.0
```
</details></p>

**Comment by angelozerr** [comment]
Thanks @jayadeepk 

@datho7561 could you test with the given sample project please.
