### ISSUE TITLE
NullPointerException with symbols

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4mp#66]
I have not studied the problem, but I did a stupid copy/paste of the following content in the` microprofile-config.properties` editor:

```
Caused by: java.lang.NullPointerException
    at org.eclipse.lsp4mp.model.Property.getResolvedPropertyValue(Property.java:181)
    at org.eclipse.lsp4mp.model.PropertyValueExpression.getResolvedValue(PropertyValueExpression.java:68)
    at org.eclipse.lsp4mp.services.MicroProfileHover.getPropertyValueExpressionHover(MicroProfileHover.java:221)
    at org.eclipse.lsp4mp.services.MicroProfileHover.doHover(MicroProfileHover.java:84)
    at org.eclipse.lsp4mp.services.MicroProfileLanguageService.doHover(MicroProfileLanguageService.java:106)
    at org.eclipse.lsp4mp.ls.ApplicationPropertiesTextDocumentService.lambda$hover$3(ApplicationPropertiesTextDocumentService.java:187)
    at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
    ... 7 more
```

and outline is empty and we have a NullPointerException:

```
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4mp.services.MicroProfileSymbolsProvider.findDocumentSymbols(MicroProfileSymbolsProvider.java:93)
	at org.eclipse.lsp4mp.services.MicroProfileLanguageService.findDocumentSymbols(MicroProfileLanguageService.java:129)
	at org.eclipse.lsp4mp.ls.ApplicationPropertiesTextDocumentService.lambda$documentSymbol$7(ApplicationPropertiesTextDocumentService.java:198)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more
```

**Comment by angelozerr** [comment]
Ok after some test, it crashed with just this content:

`.`

The NPE comes from https://github.com/eclipse/lsp4mp/blob/55ac697e9382db279480d992a993f17bc7a92c60/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/services/MicroProfileSymbolsProvider.java#L93
